spring:
    application:
        name: gtc-trading-gateway
    jackson:
        property-naming-strategy: SNAKE_CASE
        locale: en_US
        serialization:
            fail-on-empty-beans: false
            write_dates_as_timestamps: false
    jmx:
        enabled: false
server:
    address: 127.0.0.1
    servlet:
        path: /api
    port: 8084
    tomcat:
        max-threads: 4
app:
    gdax:
        restBase:
        wsBase:
        passphrase: ${GDAX_PASSPHRASE}
        publicKey: ${GDAX_PUBLIC}
        secretKey: ${GDAX_SECRET}
        pairs:
            BTC-USD=BTC-USD,
            LTC-BTC=LTC-BTC,
            XMR-BTC=XMR-BTC
        ratePerM: 60
    binance:
        restBase: "https://api.binance.com"
        passphrase: ${BINANCE_PASSPHRASE}
        publicKey: ${BINANCE_PUBLIC}
        secretKey: ${BINANCE_SECRET}
        pairs:
            LTC-BTC=LTCBTC,
            ETH-BTC=ETHBTC,
            XRP-BTC=XRPBTC,
            NEO-BTC=NEOBTC,
            OMG-BTC=OMGBTC,
            LSK-BTC=LSKBTC,
            NANO-BTC=NANOBTC,
            QTUM-BTC=QTUMBTC,
            ZEC-BTC=ZECBTC,
            DASH-BTC=DASHBTC,
            EOS-BTC=EOSBTC,
            GAS-BTC=GASBTC,
            XMR-BTC=XMRBTC,
            ADA-BTC=ADABTC,
            TRX-BTC=TRXBTC,
            NANO-BTC=NANOBTC
        ratePerM: 50
        createRatePerM: 10
    bitfinex:
        restBase: "https://api.bitfinex.com"
        wsBase: "wss://api.bitfinex.com/ws/2"
        passphrase: ${BITFINEX_PASSPHRASE}
        publicKey: ${BITFINEX_PUBLIC}
        secretKey: ${BITFINEX_SECRET}
        pairs:
            BTC-USD=BTCUSD,
            LTC-BTC=LTCBTC,
            XMR-BTC=XMRBTC,
            DASH-BTC=DASHBTC
        customCurrencyName:
            BTC=bitcoin,
            LTC=litecoin,
            XMR=monero
        ratePerM: 50
        createRatePerM: 10
    hitbtc:
        restBase: "https://api.hitbtc.com/api/2"
        wsBase: "wss://api.hitbtc.com/api/2/ws"
        publicKey: ${HITBTC_PUBLIC}
        secretKey: ${HITBTC_SECRET}
        pairs:
            # USD is actually usdt
            LTC-BTC=LTCBTC,
            ETH-BTC=ETHBTC,
            XRP-BTC=XRPBTC,
            DASH-BTC=DASHBTC,
            NEO-BTC=NEOBTC,
            OMG-BTC=OMGBTC,
            LSK-BTC=LSKBTC,
            QTUM-BTC=QTUMBTC,
            ZEC-BTC=ZECBTC,
            EOS-BTC=EOSBTC,
            XMR-BTC=XMRBTC,
            ADA-BTC=ADABTC,
            TRX-BTC=TRXBTC,
            NANO-BTC=NANOBTC
        customResponseCurrencyMapping:
            USD=USDT
        ratePerM: 10
        minRequestSeparationMs: 30
    wex:
        restBase: "https://wex.nz/tapi"
        publicKey: ${WEX_PUBLIC}
        secretKey: ${WEX_SECRET}
        pairs:
            BTC-USD=btc_usd,
            LTC-BTC=ltc_btc,
            DASH-BTC=dsh_btc,
            DASH-LTC=dsh_ltc,
            ZEC-BTC=zec_btc
        customResponseCurrencyMapping:
            dsh=DASH
        ratePerM: 50
        createRatePerM: 10
    huobi:
        restBase: "https://api.huobi.pro"
        publicKey: ${HUOBI_PUBLIC}
        secretKey: ${HUOBI_SECRET}
        pairs:
            LTC-BTC=ltcbtc,
            ETH-BTC=ethbtc,
            XRP-BTC=xrpbtc,
            DASH-BTC=dashbtc,
            NEO-BTC=neobtc,
            OMG-BTC=omgbtc,
            LSK-BTC=lskbtc,
            QTUM-BTC=qtumbtc,
            ZEC-BTC=zecbtc,
            EOS-BTC=eosbtc,
            GAS-BTC=gasbtc,
            XMR-BTC=xmrbtc,
            ADA-BTC=adabtc,
            TRX-BTC=trxbtc
        ratePerM: 50
        minRequestSeparationMs: 15
        createRatePerM: 10
    therocktrading:
        restBase: "https://api.therocktrading.com"
        publicKey: ${THEROCKTRADING_PUBLIC}
        secretKey: ${THEROCKTRADING_SECRET}
        pairs:
            BTC-USD=BTCUSD,
            LTC-BTC=LTCBTC,
            ETH-BTC=ETHBTC,
            ZEC-BTC=ZECBTC,
            DASH-BTC=DSHBTC,
            DASH-LTC=DSHLTC
        customResponseCurrencyMapping:
            dsh=DASH
        ratePerM: 5
        createRatePerM: 5
    okex:
        restBase: "https://www.okex.com/api/v1"
        wsBase: "wss://real.okex.com:10441/websocket"
        publicKey: ${OKEX_PUBLIC}
        secretKey: ${OKEX_SECRET}
        pairs:
            LTC-BTC=ltc_btc,
            ETH-BTC=eth_btc,
            XRP-BTC=xrp_btc,
            DASH-BTC=dash_btc,
            NEO-BTC=neo_btc,
            OMG-BTC=omg_btc,
            LSK-BTC=lsk_btc,
            QTUM-BTC=qtum_btc,
            ZEC-BTC=zec_btc,
            EOS-BTC=eos_btc,
            XMR-BTC=xmr_btc,
            TRX-BTC=trx_btc,
            NANO-BTC=nano_btc,
            GAS-BTC=gas_btc
        ratePerM: 30
        createRatePerM: 60
        minRequestSeparationMs: 30
    mock:
        restBase: "http://localhost:9090/api"
        publicKey: trade-gateway
        pairs:
            BTC-USDT=BTCUSDT
        customResponseCurrencyMapping:
            Bitcoin=BTC,
            Tether=USDT
        ratePerM: 50
        createRatePerM: 10
    clients:
        # all-clients: bitfinex,binance,wex,hitbtc,okex
        # mocks (need MOCK_ENABLED as true): mock-asia,mock-europe
        active: bitfinex,binance,wex,hitbtc,huobi,therocktrading,okex
    schedule:
        poolSize: 5
        puppeteerS: 10
        pingMs: 5000
    async:
        pool:
            core: 10
            max: 50
    statistics:
        enabled: true
        reportIntervalMs: 60000
        window: 1000
    rate-equalizer:
        queueCapacity: 200
        requestsPerSec: 1

